mindmap
  root((Residential Property))
    (Property Level Protection)
      (Temporary Protection)
        (External Fittings)
          (Flood barriers/gates)
          (Sandbags)
          (Flood panels)
          (Airbrick covers)
        (Internal Fittings)
          (Toilet bungs)
          (Removeable door seals)
      (Permanent Protection)
        (Flood resilience construction)
          (Raised threshold)
          (Waterproof wall sealant)
          (Cavity wall membrane)
          (Flood resiliant doors/windows)
          (Raised foundations)
          (Reinforced walls)
        (Internal Fittings)
          (Elevated electrical)
          (Non-return valves)
          (Sump pump systems)
          (Waterproof flooring)
          (Drainage systems)
        (External Fittings)
          (Permeable paving)
          (Drainage systems)
          (Landscaping)
      (Natural Protection)
        (Environmental Fittings)
          (Rain gardens)
          (Green roofs)
          (Bioswales)
          (Water storage)
        (External Fittings)
          (Detention ponds)
          (Strategic tree planting)
    (EPC Rating)
      (Walls)
        (Wall construction type)
        (Cavity wall insulation)
        (Thermal bridging)
        (Room heights)
      (Insulation)
        (Cavity wall insulation)
        (Loft insulation)
        (Floor insulation)
      (Energy)
        (Heating system)
        (Hot water)
        (Lighting)
        (Estimated costs)
        (CO2 emissions)
        (Primary energy use)
      (Windows)
        (Draught proofing)
        (Air tightness)
        (Glazing type)
        (Frame type)
      (Renewable energy systems)
        (Solar panels)
        (Heat pumps)
    (Hazard curve)
      (Location)
        (Easting/Northing)
        (Distance from watercourse)
        (Soil type)
        (Urban/rural)
        (Elevation)
      (Floor)
        (Floor level)
      (Surrounding area)
        (Nearby topography)
        (Hazard parameters)
    (Vulnerability curve)
      (Foundations)
        (Height above ground)
        (Basement status)
        (Foundation type)
        (Construction type)
      (Occupancy Type)
        (Contents value density)
        (Property type material)
        (Property type structure)
        (Square footage)
        (Extensions)